theme: jekyll-theme-minimal
title: "Stefano Ninfole"
description: |-
  Hello! ğŸ‘‹ I am Stefano, a PhD researcher in Economics at NMBU, specializing in
  ğŸŒ Carbon storage market analysis,
  âš¡ Direct Air Capture (DAC) and electricity market dynamics,
  ğŸ“Š Econometrics of emissions and emission forecasting.
  I have a background in Economics and Finance from UniversitÃ  del Salento, where I completed my Masterâ€™s thesis in advanced econometrics. I am based in Oslo, but I am currently staying in Berlin as a visiting PhD researcher at DIW.
  When I am not in the office, I love playing music and discovering new genres and artists. I am also intrigued by the intersections between modern economic reasoning and philosophical and ethical considerations.
  If you want to get in touch, just send me an email!
name: "Stefano Ninfole"
email: "stefano.ninfole@nmbu.no"
